import React from 'react';

export const onRenderBody = ({ setHeadComponents }) => {
  setHeadComponents([
    <link
      key="butler-light"
      rel="preload"
      href="/font/Butler-Light.woff2"
      as="font"
      type="font/woff2"
      crossOrigin="anonymous"
    />,
    <link
      key="butler-medium"
      rel="preload"
      href="/font/Butler-Medium.woff2"
      as="font"
      type="font/woff2"
      crossOrigin="anonymous"
    />,
    <link
      key="butler-bold"
      rel="preload"
      href="/font/Butler-Bold.woff2"
      as="font"
      type="font/woff2"
      crossOrigin="anonymous"
    />,
    <link
      key="poppins-bold"
      rel="preload"
      href="/font/Poppins-Bold.woff2"
      as="font"
      type="font/woff2"
      crossOrigin="anonymous"
    />,
    <link
      key="poppins-medium"
      rel="preload"
      href="/font/Poppins-Medium.woff2"
      as="font"
      type="font/woff2"
      crossOrigin="anonymous"
    />,
    <link
      key="newsreader"
      rel="preload"
      href="/font/Newsreader16pt-Regular.woff2"
      as="font"
      type="font/woff2"
      crossOrigin="anonymous"
    />,
    <link
      key="newsreader-italic"
      rel="preload"
      href="/font/Newsreader16pt-Italic.woff2"
      as="font"
      type="font/woff2"
      crossOrigin="anonymous"
    />,
  ]);
};
